version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: notion_clone_db
    environment:
      POSTGRES_DB: notion_clone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notion_network

  # Redis (for caching and real-time features)
  redis:
    image: redis:7-alpine
    container_name: notion_clone_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - notion_network

  # Backend API
  backend:
    build: ./backend
    container_name: notion_clone_backend
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/notion_clone
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-super-secret-key-change-in-production
      - ENVIRONMENT=development
      - DEBUG=true
      - ALLOWED_ORIGINS=["http://localhost:3000"]
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    networks:
      - notion_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend (Next.js)
  frontend:
    build: ./frontend
    container_name: notion_clone_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - notion_network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  notion_network:
    driver: bridge 